In [ ]:
from sklearn.datasets import load_breast_cancer
import pandas

cancer = load_breast_cancer()
df_cancer = pandas.DataFrame(cancer.data,columns=cancer.feature_names)
df_cancer['label'] = pandas.Series(cancer.target)
df_cancer.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  label  
0          0.4601                  0.11890      0  
1          0.2750                  0.08902      0  
2          0.3613                  0.08758      0  
3          0.6638                  0.17300      0  
4          0.2364                  0.07678      0  

[5 rows x 31 columns]

In [ ]:
data = df_cancer
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [ ]:
data.describe

<bound method NDFrame.describe of      mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean c

In [ ]:
data.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
label                      0
dtype: int64

In [ ]:
display(data.head())

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  label  
0          0.4601                  0.11890      0  
1          0.2750                  0.08902      0  
2          0.3613                  0.08758      0  
3          0.6638                  0.17300      0  
4          0.2364                  0.07678      0  

[5 rows x 31 columns]

In [ ]:
display(data.describe())

mean radius  mean texture  mean perimeter    mean area  \
count   569.000000    569.000000      569.000000   569.000000   
mean     14.127292     19.289649       91.969033   654.889104   
std       3.524049      4.301036       24.298981   351.914129   
min       6.981000      9.710000       43.790000   143.500000   
25%      11.700000     16.170000       75.170000   420.300000   
50%      13.370000     18.840000       86.240000   551.100000   
75%      15.780000     21.800000      104.100000   782.700000   
max      28.110000     39.280000      188.500000  2501.000000   

       mean smoothness  mean compactness  mean concavity  mean concave points  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       mean symmetry  mean fractal dimension  ...  worst texture  \
count     569.000000              569.000000  ...     569.000000   
mean        0.181162                0.062798  ...      25.677223   
std         0.027414                0.007060  ...       6.146258   
min         0.106000                0.049960  ...      12.020000   
25%         0.161900                0.057700  ...      21.080000   
50%         0.179200                0.061540  ...      25.410000   
75%         0.195700                0.066120  ...      29.720000   
max         0.304000                0.097440  ...      49.540000   

       worst perimeter   worst area  worst smoothness  worst compactness  \
count       569.000000   569.000000        569.000000         569.000000   
mean        107.261213   880.583128          0.132369           0.254265   
std          33.602542   569.356993          0.022832           0.157336   
min          50.410000   185.200000          0.071170           0.027290   
25%          84.110000   515.300000          0.116600           0.147200   
50%          97.660000   686.500000          0.131300           0.211900   
75%         125.400000  1084.000000          0.146000           0.339100   
max         251.200000  4254.000000          0.222600           1.058000   

       worst concavity  worst concave points  worst symmetry  \
count       569.000000            569.000000      569.000000   
mean          0.272188              0.114606        0.290076   
std           0.208624              0.065732        0.061867   
min           0.000000              0.000000        0.156500   
25%           0.114500              0.064930        0.250400   
50%           0.226700              0.099930        0.282200   
75%           0.382900              0.161400        0.317900   
max           1.252000              0.291000        0.663800   

       worst fractal dimension       label  
count               569.000000  569.000000  
mean                  0.083946    0.627417  
std                   0.018061    0.483918  
min                   0.055040    0.000000  
25%                   0.071460    0.000000  
50%                   0.080040    1.000000  
75%                   0.092080    1.000000  
max                   0.207500    1.000000  

[8 rows x 31 columns]

In [ ]:
x= data.drop(['label'], axis =1)
y = data['label']

In [ ]:
from sklearn.preprocessing import LabelEncoder
en = LabelEncoder()
data['label'] = en.fit_transform(data['label'])

In [ ]:
x.head(4)

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  

[4 rows x 30 columns]

In [ ]:
y.head(4)

0    0
1    0
2    0
3    0
Name: label, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20)



In [ ]:
x_train

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
490        12.25         22.44           78.18      466.5          0.08192   
319        12.43         17.00           78.60      477.3          0.07557   
344        11.71         15.45           75.03      420.3          0.11500   
74         12.31         16.52           79.19      470.9          0.09172   
346        12.06         18.90           76.66      445.3          0.08386   
..           ...           ...             ...        ...              ...   
120        11.41         10.82           73.34      403.3          0.09373   
40         13.44         21.58           86.18      563.0          0.08162   
298        14.26         18.17           91.22      633.1          0.06576   
236        23.21         26.97          153.50     1670.0          0.09509   
188        11.81         17.39           75.27      428.9          0.10070   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
490           0.05200         0.01714             0.012610         0.1544   
319           0.03454         0.01342             0.016990         0.1472   
344           0.07281         0.04006             0.032500         0.2009   
74            0.06829         0.03372             0.022720         0.1720   
346           0.05794         0.00751             0.008488         0.1555   
..                ...             ...                  ...            ...   
120           0.06685         0.03512             0.026230         0.1667   
40            0.06031         0.03110             0.020310         0.1784   
298           0.05220         0.02475             0.013740         0.1635   
236           0.16820         0.19500             0.123700         0.1909   
188           0.05562         0.02353             0.015530         0.1718   

     mean fractal dimension  ...  worst radius  worst texture  \
490                 0.05976  ...         14.17          31.99   
319                 0.05561  ...         12.90          20.21   
344                 0.06506  ...         13.06          18.16   
74                  0.05914  ...         14.11          23.21   
346                 0.06048  ...         13.64          27.06   
..                      ...  ...           ...            ...   
120                 0.06113  ...         12.82          15.97   
40                  0.05587  ...         15.93          30.25   
298                 0.05586  ...         16.22          25.26   
236                 0.06309  ...         31.01          34.51   
188                 0.05780  ...         12.57          26.48   

     worst perimeter  worst area  worst smoothness  worst compactness  \
490            92.74       622.9           0.12560            0.18040   
319            81.76       515.9           0.08409            0.04712   
344            84.16       516.4           0.14600            0.11150   
74             89.71       611.1           0.11760            0.18430   
346            86.54       562.6           0.12890            0.13520   
..               ...         ...               ...                ...   
120            83.74       510.5           0.15480            0.23900   
40            102.50       787.9           0.10940            0.20430   
298           105.80       819.7           0.09445            0.21670   
236           206.00      2944.0           0.14810            0.41260   
188            79.57       489.5           0.13560            0.10000   

     worst concavity  worst concave points  worst symmetry  \
490          0.12300               0.06335          0.3100   
319          0.02237               0.02832          0.1901   
344          0.10870               0.07864          0.2765   
74           0.17030               0.08660          0.2618   
346          0.04506               0.05093          0.2880   
..               ...                   ...             ...   
120          0.21020               0.08958         

In [ ]:
y_train

490    1
319    1
344    1
74     1
346    1
      ..
120    1
40     0
298    1
236    0
188    1
Name: label, Length: 455, dtype: int64

In [ ]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
model  = LogisticRegression()
model.fit(x_train, y_train)

LogisticRegression()

In [ ]:
model_predict = model.predict(x_test)
model_predict

array([1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1])

In [ ]:
score = model.score(x_test, y_test)

In [ ]:
y.unique()

array([0, 1])

In [ ]:
y.value_counts()

1    357
0    212
Name: label, dtype: int64

In [ ]:
score

0.9912280701754386

In [ ]:
import numpy as np

In [ ]:
y_pred=model.predict(x_test)

In [ ]:
y_pred

array([1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1])

In [ ]:
from sklearn import metrics
print ( metrics.confusion_matrix(y_test, y_pred, labels=[0,1]))
print( metrics.classification_report(y_test, y_pred, labels= [0,1]))

[[46  1]
 [ 0 67]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99        47
           1       0.99      1.00      0.99        67

    accuracy                           0.99       114
   macro avg       0.99      0.99      0.99       114
weighted avg       0.99      0.99      0.99       114



In [ ]:
x_test

array([[-0.56415856, -1.37952607, -0.56249639, ..., -0.61220003,
        -0.19191231, -0.19315131],
       [ 1.21241159, -0.11118429,  1.14869159, ...,  0.99978006,
        -0.14263729, -0.10997221],
       [-1.20632367, -0.85630589, -1.18341437, ..., -0.74670016,
        -0.63538746,  0.46601457],
       ...,
       [-0.37639098, -0.39148082, -0.43060889, ..., -1.20011329,
        -1.17105459, -1.34797346],
       [-0.45149801,  0.12706776, -0.45363687, ..., -0.57612601,
        -0.34450591, -0.35723063],
       [-0.78659092, -0.27001899, -0.72578568, ...,  0.13213764,
         0.64576299,  2.60873095]])